### PR TITLE
Allow to pass several options to PhantomJS via jasmine.yml. Fix #192

### LINKED ISSUE #192: "phantom_options: --debug=true" fails with "Invalid values for 'debug' option."
jasmine-rails 0.11.0
phantomjs 1.9.8

Steps to reproduce:
1. Add the following to `jasmine.yml`
    `phantom_options: --debug=true`
2. Run the jasmine rake task from the command line, `rake spec:javascript`
3. The rake task will error out with "Invalid values for 'debug' option."
4. Verify the debug option is valid by running `phantomjs --debug=true`

Expected Results:
To run phantomjs with the debug option enabled.

### PR DESCRIPTION
**Pull request by bolshakov**
Currently it doesn't work. See #192 

```yml
phantom_options: --debug=true --web-security=false
```

### CODE REVIEW

**Comment by searls** [comment]
Could you please fix this build failure prior to merge -- glancing at it, I presume it's blowign up on a nil for users who do not provide custom options: https://travis-ci.org/searls/jasmine-rails/jobs/272800047

**Comment by searls** [comment]
Also, as a user I'd expect this to work if they provide:

`phantom_options: --one-thing --two-thing=true`

I wouldn't expect to have to break out a yaml list for each CLI arg since they're normally space-delimited, so I'd  recommend just splitting on whitespace (e.g. `split(/\s+/)` instead of dealing with YAML arrays.

**Comment by bolshakov** [comment]
It works on ruby >= 2.0

**Comment by searls** [comment]
Thanks for making the change so quickly

**Comment by searls** [comment]
landed in 0.14.2

**Comment by bolshakov** [comment]
Woohoo! Thanks

**Pull request merged**
