### PR TITLE
PhantomJS (2.1.1) crashes when the url is not followed by a newline

### PR DESCRIPTION
**Pull request by dkanai**
PhantomJS WebPage.open doesn't work when the url has no newline at the end.

### CODE REVIEW

**Comment by searls** [comment]
What's this require("system") business?

**Comment by terryyin** [comment]
console.error will raise another error which led to the endless recursion.

If you still want to output the stderr, then require("system") is a way of doing it. Otherwise just output to STDOUT.

BTW, is there a way to unit test this piece or code?

**Comment by searls** [comment]
Ah, I see. As for a way to unit test it, not beyond the existing test of the functionality this replaces.

Unfortunately it looks like most of the build is broken due to a breaking nokogiri version, so we should probably fix that first, since I'm not sure when `require('system')` was introduced to phantom

**Comment by searls** [comment]
can you update the PR and get the build passing?

**Pull request closed without merging**
