### PR TITLE
rails root path for jasmine jquery

### PR DESCRIPTION
**Pull request by fmachella**
I added to query string the rails root in order to  allow jasmine jquery to load fixtures

### CODE REVIEW

**Comment by searls** [comment]
Hi -- I don't remember anything about this PR or what issue it ties back to -- can you help explain the purpose of this PR and what it fixes?

**Comment by fmachella** [comment]
Hi Justing, I'm using jasmine jquery that allow me to load fixtures by a folder. Anyway it refer to a relative path that is the phantomjs bin path instead of rails root path. I did not find any other smart way to pass the rails root path rather than this, passing trough query.

**Comment by searls** [comment]
since this is just adding a query parameter that jasmine itself doesn't look at and it seems to solve your problem, i'll merge it

**Comment by fmachella** [comment]
Thanks

**Pull request merged**
