### PR TITLE
remove wrong workaround

### PR DESCRIPTION
**Pull request by fmachella**
we have to remove the workaround that is catched by spec filter as blank and this let skill all tests

### CODE REVIEW

**Comment by searls** [comment]
Can you explain?

**Comment by fmachella** [comment]
You can reproduce by command line, just copy and paste the command executed by rake  spec:javascript.
the address that we modified append just after the query string "spec=" a newline character.
The result is that the spec filter parse a "spec=\n" and accept newline as parameter, this means that all test are skipped. I tried to modify gem in local and works.
The guy suggested 2 modification in code but only the second (console log looping) is the one that  fixes really the problem.

**Comment by searls** [comment]
Ok will revert and relaunch. In the future to fix this issue I'm going to insist we have a test case for it.

**Comment by searls** [comment]
landed in 0.14.7

**Comment by fmachella** [comment]
We should implement also a test suite in order to avoid this confusing bugfix

**Pull request merged**
